apiVersion: apps/v1
kind: Deployment

metadata:
  name: client-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      client: web

  template:
    metadata:
      labels:
        client: web

    spec:
      containers:
        - name: client
          image: byznass/tiolktrack-client
          ports:
            - containerPort: 80