apiVersion: apps/v1
kind: Deployment

metadata:
  name: server-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      client: web

  template:
    metadata:
      labels:
        client: web

    spec:
      containers:
        - name: server
          image: byznass/tiolktrack-server
          ports:
            - containerPort: 80